// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/lib')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/lib')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/lib')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElLink: typeof import('element-plus/lib')['ElLink']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElScrollbar: typeof import('element-plus/lib')['ElScrollbar']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTable: typeof import('element-plus/lib')['ElTable']
    ElTableColumn: typeof import('element-plus/lib')['ElTableColumn']
    ElTag: typeof import('element-plus/lib')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
